### ISSUE TITLE
Load-balancing solution for on-prem deployments

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-package-metallb#4]
To support istio service loadbalancers on-prem we will need a load balancing solution in cluster.

Options I know about:
- [MetalLB](https://metallb.universe.tf/)
- [kube-vip](https://kube-vip.io/)
- [Calico + MetalLB](https://itnext.io/kubernetes-service-type-lb-for-on-prem-deployments-89e9b2a73a0c) - only wise if we wanted to use Calico

Requirements:
- Istio services of type load balancer able to provision
- Automated install/config of load balancing solution
```[tasklist]
### Tasks
- [ ] Identify load balancing solution
- [ ] Deploy solution manually on top of RKE2
- [ ] Automate deployment/configuration in existing on-prem zarf package
```

**Comment by mjnagel** [comment]
Moved this issue to metallb repo - if a different solution is chosen we could certainly rename the repo or move again as needed.

**Comment by bburky** [comment]
Thanks @mjnagel 

The main note for our use case is that we needed to set the ethernet interface, our on-prem servers may have multiple NICs which may be attached to different networks and we need to select the right one. I think `.spec.interfaces: null` in a L2Advertisement would leave you on the default (all interfaces) config, perhaps add a zarf variable to configure the interface with "null" as the default value? That would let users still configure it, but the default config still works out of the box.
